name: Docker React CI
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ingjulianvega/docker-react -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true ingjulianvega/docker-react npm run test
      # Nuevo bloque para construir y subir la imagen automáticamente
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ingjulianvega/docker-react:latest
      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster react-cluster-v2 --service react-frontend-service --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1